from pathlib import Path
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from datetime import datetime, timedelta
from esea import Match
from config import config
from typing import Dict

# If modifying these scopes, delete the .cache directory.
SCOPES = [
    "https://www.googleapis.com/auth/calendar.readonly",
    "https://www.googleapis.com/auth/calendar.events",
]

CREDENTIALS_PATH = Path.cwd() / "credentials.json"
CACHE_PATH = Path.cwd() / ".cache"
TOKEN_PATH = CACHE_PATH / "token.json"

CACHE_PATH.mkdir(exist_ok=True)

creds = None
if TOKEN_PATH.exists():
    creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_PATH, SCOPES)
        creds = flow.run_local_server(port=0)
    with open(TOKEN_PATH, "w+") as token:
        token.write(creds.to_json())

service = build("calendar", "v3", credentials=creds)


def get_events(start: datetime, end: datetime):
    return (
        service.events()
        .list(
            calendarId=config.google_calendar_id,
            timeMin=start.isoformat(),
            timeMax=end.isoformat(),
            singleEvents=True,
            orderBy="startTime",
        )
        .execute()
        .get("items", [])
    )


def get_match_event(match: Match) -> Dict:
    return {
        "start": {
            "dateTime": match.date.isoformat(),
        },
        "end": {"dateTime": (match.date + timedelta(hours=1)).isoformat()},
        "reminders": {"useDefault": True},
        "summary": match.title,
        "description": f"Auto generated by ESEA script.",
        "location": match.map,
    }


def create_match_event(match: Match):
    service.events().insert(
        calendarId=config.google_calendar_id, body=get_match_event(match)
    ).execute()


def update_match_event(match: Match, event: Dict):
    service.events().update(
        calendarId=config.google_calendar_id,
        eventId=event["id"],
        body=event | get_match_event(match),
    )


def create_or_update_match(match: Match) -> None:
    events = get_events(
        match.date - timedelta(minutes=1), match.date + timedelta(hours=1, minutes=1)
    )
    existing_event = None
    for event in events:
        if event["summary"] == match.title:
            existing_event = event
            break
    else:
        print(f"Creating new event for {match}")
        create_match_event(match)
        return
    print(f"Updating existing event for {match}")
    update_match_event(match, existing_event)
